# Generated by Django 5.1.3 on 2025-03-06 13:44

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetrequest',
            name='expires_at',
            field=models.DateTimeField(default=account.models.get_default_expires_at),
        ),
        migrations.AddField(
            model_name='passwordresetrequest',
            name='new_password',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='passwordresetrequest',
            name='old_password',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
