# Generated by Django 5.1.3 on 2025-03-15 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='logo',
            field=models.ImageField(upload_to='partner_logos/'),
        ),
    ]
