# Generated by Django 5.1.3 on 2025-03-21 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Innovation_WebApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventregistration',
            name='uid',
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
