# Generated by Django 5.1.3 on 2025-03-21 08:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Innovation_WebApp', '0002_remove_eventregistration_uid_eventregistration_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventregistration',
            name='id',
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
