# Generated by Django 5.1.3 on 2025-02-28 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Innovation_WebApp', '0026_alter_events_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social_media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=50)),
                ('url', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='communityprofile',
            name='github_link',
        ),
        migrations.RemoveField(
            model_name='communityprofile',
            name='linkedin_link',
        ),
        migrations.AlterField(
            model_name='events',
            name='category',
            field=models.CharField(choices=[('WEB', 'Web Development'), ('CYBERSEC', 'Cyber Security'), ('ANDROID', 'Android Development'), ('AI', 'Artificial Intelligence'), ('BLOCKCHAIN', 'Blockchain'), ('IoT', 'Internate of Things')], default='Web Development', max_length=50),
        ),
        migrations.AddField(
            model_name='communityprofile',
            name='social_media',
            field=models.ManyToManyField(related_name='communities', to='Innovation_WebApp.social_media'),
        ),
    ]
