# Generated by Django 5.1.3 on 2025-02-28 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AboutUs', '0006_rename_description_club_about_us_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmedia',
            name='club',
        ),
        migrations.RemoveField(
            model_name='socialmedia',
            name='executive',
        ),
    ]
