# Generated by Django 5.1.3 on 2025-02-28 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AboutUs', '0007_remove_socialmedia_club_remove_socialmedia_executive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='executivemember',
            name='community',
        ),
        migrations.RemoveField(
            model_name='socialmedia',
            name='community',
        ),
        migrations.DeleteModel(
            name='Community',
        ),
    ]
